version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: todo_app
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://todo_user:todo_password@db:5432/todo_db
      ALEMBIC_DATABASE_URL: postgresql+psycopg2://todo_user:todo_password@db:5432/todo_db
      SECRET_KEY: 8c47dc98274957f7954bb7ccd97b5fee
      ACCESS_TOKEN_EXPIRE_MINUTES: 60

volumes:
  pgdata:
