"""crear tablas iniciales

Revision ID: e6d1ff0c815f
Revises: 8c8c3ee7cc5e
Create Date: 2025-09-04 17:11:49.472602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d1ff0c815f'
down_revision: Union[str, Sequence[str], None] = '8c8c3ee7cc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
